<?php
/**
 * Created by PhpStorm.
 * User: gabri
 * Date: 22/02/2017
 * Time: 17:40
 */
namespace enterprise\contactCliente;

use enterprise\model;


class webmail extends model
{
    protected $name;
    protected $email;
    protected $mensagem;


    function __construct(string $name , string $email)
    {
        $this->name = $name;
        $this->email = $email;
    }

public static function getIdAttribute()
{
    return 'name'; // TODO: Change the autogenerated stub
}

public static function getClassName()
{
    return 'webmail'; // TODO: Change the autogenerated stub
}


}

