<?php

declare (strict_types=1);
namespace enterprise\cadastroServiceCar;

use enterprise\model;

class servicosCar extends model
{
    protected $name;
    protected $email;
    protected $fone;
    protected $localizacao;
    protected $endereco;

    function __construct(string $name , string $email , string $fone)
    {
        $this->name = $name;
        $this->email = $email;
        $this->fone = $fone;
    }

    /**
     * @param mixed $localizacao
     */
    public function setLocalizacao(double $localizacao)
    {
        $this->localizacao = $localizacao;
    }

    public function setEndereço(string $endereco)
    {
        $this->endereco = $endereco;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getFone(): string
    {
        return $this->fone;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @return mixed
     */
    public function getLocalizacao()
    {
        return $this->localizacao;
    }

    /**
     * @return mixed
     */
    public function getEndereco()
    {
        return $this->endereco;
    }

    public static function getClassName()
    {
        return 'servicoCar';
    }

    public static function getIdAttribute()
    {
        return 'fone'; // TODO: Change the autogenerated stub
    }


}